site_name : Training Fahmi - DevOps
site_url: https://devops.ghamacha.com
site_author: Fahmi GHAMACHA


nav :
  - Home: index.md
  - Docker:
      - 1. Introduction: ./Docker/History/History.md
      - 2. First Steps : ./Docker/Docker.md
      - 3. Docker-compose: ./Docker/Compose/Docker-compose.md
      - 4. Docker Swarm : ./Docker/Swarm/Docker Swarm.md
  - Kubernetes: ./K8s/Kubernetes.md
  - Cloud: 
      - Fondamentaux Azure: ./Cloud/Azure01.md
      - AWS: ./Cloud/AWS01.md
      - Google Cloud: ./Cloud/Google.md
  - Infrastructure as a Code: 
      - Terraform: ./Iaac/Terraform.md
      - Vagrant: ./Iaac/Vagrant.md
      - Ansible: ./Iaac/Ansible.md


theme:
  name: mkdocs
  language: en
  highlightjs: true
  hljs_languages:
    - yaml
    - shell
    - bat
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
  features:
    - navigation.tabs
    - navigation.tabs.sticky

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - markdown.extensions.attr_list

extra:
  generator: false
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/fahmighamacha
      name: Find me on LinkedIn

copyright: Copyright &copy; 2022 <a href="https://www.linkedin.com/in/fahmighamacha">Fahmi GHAMACHA</a>. All rights reserved.

plugins:
    - search